#database configurations
db:
  host : "localhost"
  port : "3306"
  user : "pardhu"
  password : "5915"
  database : "mysql"
#http configurations
http:
  host : "0.0.0.0"
  port : "8082"
  path : "scatter"